[package]
name = "m7o"
version = "0.1.0"
edition = "2024"

[dependencies]
k8s-openapi = { version = "0.26.0", features = ["v1_33"] }
kube = { version = "2.0.1", features = ["runtime", "derive"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
